service:
  type: NodePort

ingress:
  enabled: true
  annotations: 
    kubernetes.io/tls-acme: "true"
    kubernetes.io/ingress.class: "gce"

server:
  env:
    DRONE_OPEN: false
    DRONE_ADMIN: Noah-Huppert
