pipeline:
  helm_deploy:
    image: quay.io/ipedrazas/drone-helm
    skip_tls_verify: true
    chart: ./deploy/noahhuppert-com
    release: noahhuppert-com
    debug: true
    wait: true
    when:
      branch: [master]

