pipeline:
  docker:
    image: plugins/docker
    repo: noahhuppert/noahhuppert-com
    tags: 
      - latest
      - ${DRONE_COMMIT}
    when:
      branch: [ master ]
      event: [ push, tag, deployment ]
    secrets: [ docker_username, docker_password ]

  helm_deploy:
    image: quay.io/ipedrazas/drone-helm
    skip_tls_verify: true
    chart: ./deploy/noahhuppert-com
    release: noahhuppert-com
    namespace: noahhuppert-com
    values: image.tag=${DRONE_COMMIT}
    wait: true
    when:
      branch: [ master ]
      event: [ push, tag, deployment ]
    secrets: [ api_server, secret_password, kubernetes_token ]

