pipeline:
  docker:
    image: plugins/docker
    repo: noahhuppert/noahhuppert-com
    tags: latest
    secrets: [ docker_username, docker_password ]

  helm_deploy:
    image: quay.io/ipedrazas/drone-helm
    skip_tls_verify: true
    chart: ./deploy/noahhuppert-com
    release: noahhuppert-com
    debug: true
    wait: true
    when:
      branch: [master]
    secrets: [ api_server, secret_password, kubernetes_token ]

