# Use container based infrastructure
sudo: false

language: ruby
rvm:
    - 2.2.2

# Use MySQL database for tests
services:
    # - mysql

before_script:
    # Setup MySQL database for tests
    # - mysql -e 'CREATE DATABASE onyx_test'
    # Install Bower libs
    # - npm install -g bower
    # - bower install

# Run tests, right now there are none, so return 0
script: return 0

# Deploy to Dokku
after_success:
    - git config --global user.email "noahhuppert@gmail.com"
    - git config --global user.name "Noah Huppert"
    - git add remote dokku dokku@noahhuppert.com:www
    - git push dokku master

env:
    - RACK_ENV=test
