language: ruby
rvm:
- 2.2.2
script: return 0
env:
- RACK_ENV=test
deploy:
  provider: openshift
  user: noahhuppert@gmail.com
  password:
    secure: GODmU1SxOafBKN5EtqZzHZGx+WlV9wBnFn66D3HjTsUVyuWrWFzJQ9RR0PElibyw9+fX4xt4ThaK4HhcgP8YNmy+T1NgIz7ZNGM2yWF9bMyGeCMKKnbdZ9oAvKod3PVtZOsxdfl+h0mU+IDySDr2nu34adyX5sZe/Dy6XMiq0X4=
  app: onyx
  domain: http://onyx-noahhuppert.rhcloud.com/
  on:
    repo: Noah-Huppert/NoahHuppert.com
    branch: onyx-sinatra
