language: ruby
rvm:
- 2.2.2
script: return 0
deploy:
  provider: openshift
  user: noahhuppert@gmail.com
  password:
    secure: M3I03y8uol8NlccSm2k2hQ6VUk5PLRO6UKJmNqQ2BaAihcbUnhKu34/vEjv8eiGebPSFkiDt/H3DB3G7qKxh1kv2z+jrBB+WZCyY40bWST4OJeLDg1MFA2zt5ydb2hSjKek5tEv12j7g7cZ5PmMlP+bil43OxaJ1peR2PTbu8w8=
  app: onyx
  domain: http://onyx-noahhuppert.rhcloud.com/
  on:
    repo: Noah-Huppert/NoahHuppert.com
    branch: onyx-sinatra
env:
  - RACK_ENV=test
