FORMAT: 1A
HOST: https://api.noahhuppert.com

#Onyx
The backend for NoahHuppert.com using Ruby On Rails

For information on the stack setup of NoahHuppert.com go to the [Github Repository](https://github.com/Noah-Huppert/NoahHuppert.com)

#Group Users
User authetication and Api credentials

##Users [/users{?access_token,page}]
###Get users [GET]
Retrieves a list of user ids
- Response 200 (application/json)

        users: [
           //An array of user Ids
        ]
- Parameters
    - access_token (string) - Api access token
    - page (number, optional) - The page of user ids to view, each page contains 
        - Default: 0