# Default values for external-dns.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
DOToken: ""
source: ingress
host: noahh.io.
dhost: noahh-io
source: ingress
provider: google
gcpProject: nh-k8s
