languageCode = "en-us"
title = "Noah Huppert"
theme = "noahhuppert-com"

[params]
  biography = '''
			  My name is Noah Huppert, I am a second year computer science 
			  major at Drexel University.
			  '''
  keybaseUsername = "noahh"
  githubUsername = "Noah-Huppert"
  twitterUsername = "NoahHuppert"

  [[params.contactEmails]]
  user = "contact"
  host = "noahh"
  tld ="io"

  [[params.contactEmails]]
  user = "contact"
  host = "noahhuppert"
  tld ="com"
