development:
  database:
    host: localhost
    port: 3306
    database: onyx_dev
    username: onyx_dev
    password: password

test:
  database:
    host: 127.0.0.1
    port: 3306
    username: onyx_test
    username: travis
    password: ''

production:
  database:
    host: _ENV_OPENSHIFT_mysql_DB_HOST
    port: _ENV_OPENSHIFT_mysql_DB_PORT
    username: _ENV_OPENSHIFT_mysql_DB_USERNAME
    password: _ENV_OPENSHIFT_mysql_DB_PASSWORD
