user:
  create: 'user.create'
  self:
    get: 'user.self.get'
    set: 'user.self.set'
    delete: 'user.self.delete'
    provider_access_token:
      get: 'user.self.provider_access_token.get'
      set: 'user.self.provider_access_token.set'
      delete: 'user.self.provider_access_token.delete'
      identity:
        get: 'user.self.provider_access_token.identity.get'
    api_access_token:
      get: 'user.self.api_access_token.get'
      set: 'user.self.api_access_token.set'
      delete: 'user.self.api_access_token.delete'
    post:
      get: 'user.self.post.get'
      set: 'user.self.post.set'
      delete: 'user.self.post.delete'
      meta:
        get: 'user.self.post.meta.get'
        set: 'user.self.post.meta.set'
        delete: 'user.self.post.meta.delete'
  peers:
    get: 'user.peers.get'
    set: 'user.peers.set'
    delete: 'user.peers.delete'
    provider_access_token:
      get: 'user.peers.provider_access_token.get'
      set: 'user.peers.provider_access_token.set'
      delete: 'user.peers.provider_access_token.delete'
    api_access_token:
      get: 'user.peers.api_access_token.get'
      set: 'user.peers.api_access_token.set'
      delete: 'user.peers.api_access_token.delete'
    post:
      get: 'user.peers.post.set'
      set: 'user.peers.post.set'
      delete: 'user.peers.post.delete'
      meta:
        get: 'user.peers.post.meta.get'
        set: 'user.peers.post.meta.set'
        delete: 'user.peers.post.meta.delete'
  permission_group:
    set: 'user.permission_group.set'
provider_access_token:
  create: 'provider_access_token.create'
api_access_token:
  create: 'api_access_token.create'
post:
  create: 'post.create'
  meta:
    create: 'post.meta.create'
