apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: external-dns-{{ .Values.dhost }}
spec:
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: external-dns
    spec:
      containers:
      - name: external-dns-{{ .Values.dhost }}
        image: registry.opensource.zalan.do/teapot/external-dns:v0.4.8
        args:
        - --source=service
        - --domain-filter={{ .Values.host }}
        - --provider={{ .Values.provider }}
        - --google-project={{ .Values.gcpProject }}
